#!/usr/bin/env ruby

class ExitCompiler
  def initialize(source_file_name)
    @source_file_name = source_file_name
  end

  def compile
    File.open(target_file_name, "w") do |target_file|
      target_file.write("define i32 @main() {\n")
      target_file.write("  ret i32 #{exit_code}\n")
      target_file.write("}\n")
    end
  end

  private

  attr_reader :source_file_name

  def target_file_name
    base_file_name + ".ll"
  end

  def base_file_name
    source_file_name.split(".")[0...-1].join(".")
  end

  def exit_code
    first_line = File.open(source_file_name).readlines[0]
    cmd, code = first_line.strip.split

    if cmd == "exit" && code =~ /[0-9]+/
      code.to_i
    else
      raise "Error on line 0: \"#{first_line}\""
    end
  end
end

ExitCompiler.new(ARGV[0]).compile
